# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            --Dabao--
tagline:          '大寶開發學習誌'
description:      '-自己整理過，才算是學習-'
url:              /
newbaseurl:       https://dabaohuang.github.io
baseurl:          https://dabaohuang.github.io/

author:
  name:           'Dabao Huang'
  url:            https://dabaohuang.github.io
  fb:             https://www.facebook.com/da.bao.12

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://www.github.com/dabaohuang

headpic:          https://avatars1.githubusercontent.com/u/4962159?v=4&amp;s=460

# Category        每當有新的 Label 時，一定要來這裡新增
categories:
  1:              'Linux'
  2:              'Unix'
