# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Dabao Dev
tagline:          '大寶開發學習誌'
description:      '-只有自己整理過的東西，才能算是自己的-'
url:              /
baseurl:          https://dabaohuang.github.io/

author:
  name:           'Dabao Huang'
  url:            https://dabaohuang.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://www.github.com/dabaohuang

headpic:          https://avatars1.githubusercontent.com/u/4962159?v=4&amp;s=460

# Category
categories:
  1:              'Linux'
